name: buildpack
on: [push, pull_request]
jobs:
  remote-build:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
      volumes:
        - /home/runner:/var/www
    env:
      IMG_NAME: "jamstack"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Downloads and caches the pack command (the code is open)
      - uses: andrioid/setup-pack@main
      # Fetches any previous image so that we may use it for caching
      - run: docker pull ghcr.io/{{ env.GITHUB_REPOSITORY }}/{{ env.IMG_NAME }}
      # Builds your site with buildpacks (heroku builder)
      - run: pack build ghcr.io/{{ env.GITHUB_REPOSITORY }}/{{ env.IMG_NAME }} --builder heroku/buildpacks:20
      # Pushes your new image to Github's Container Registry
      - run: docker push ghcr.io/{{ env.GITHUB_REPOSITORY }}/{{ env.IMG_NAME }}
