name: buildpack
on: [push, pull_request]
jobs:
  remote-build:
    runs-on: ubuntu-latest
    # container:
    #   image: docker:stable
    #   volumes:
    #     - /home/runner/workspace:/workspace
    env:
      IMG_NAME: ${{ github.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Downloads and caches the pack command (the code is open)
      - uses: andrioid/setup-pack@main
      # Attempt to fetch any previous image so that we may use it for caching
      # - run: docker pull ghcr.io/${GITHUB_REPOSITORY}/${IMG_NAME} || true
      # Builds your site with buildpacks (heroku builder)
      - run: pack build ghcr.io/${GITHUB_REPOSITORY}/${IMG_NAME} --builder=heroku/buildpacks:20 --publish --cache-image=ghcr.io/${GITHUB_REPOSITORY}/${IMG_NAME}
      # Pushes your new image to Github's Container Registry
      #- run: docker push ghcr.io/${GITHUB_REPOSITORY}/${IMG_NAME}
      - run: CONTAINER_ID=$(docker create ghcr.io/${GITHUB_REPOSITORY}/${IMG_NAME} /bin/sh) && docker cp ${CONTAINER_ID}:/workspace .
      - run: ls -alh
  # deploy:
  #   needs: remote-build
  #   runs-on: ubuntu-latest
  #   services:
  #     assets:
  #       image: ghcr.io/${{ github.repository }}/${{ github.workflow }}
  #       volumes:
  #         - /tmp/assets:/workspace
  #   env:
  #     IMG_NAME: ${{ github.workflow }}
  #   steps:
  #     - run: ls -alh /tmp/assets
